services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - ${GRADIO_SERVER_PORT}:${GRADIO_SERVER_PORT}
    env_file: .env

networks:
  default:
    driver: bridge
    name: tourism-app